version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: iknow
    volumes:
      - ./db/:/db/

  web:
    image: web
    build: .
    entrypoint: /app/artisan serve --host 0.0.0.0 --port 6660
    volumes:
      - ./app/:/app/
    ports:
      - 6660:6660

  shell:
    image: web
    volumes:
      - ./app/:/app/

  adminer:
    image: web
    volumes:
      - ./app/database/:/app/
    entrypoint: bash -c 'echo Serving on http://127.0.0.1:6661 && php -S 0.0.0.0:6661 /app/adminer.php'
    ports:
      - 6661:6661
