version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: iknow
    volumes:
      - ./db/:/var/lib/postgresql/data/

  server:
    image: web
    build: .
    restart: always
    user: root
    entrypoint: bash -c 'service php7.3-fpm start && service php7.3-fpm status && tail -fn0 /var/log/php7.3-fpm.log'
    volumes:
      - ./app/:/app/
    depends_on:
      - db

  shell:
    image: web
    volumes:
      - ./app/:/app/
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/:/app/:ro
    depends_on:
      - server
    ports:
      - 6660:80

  adminer:
    image: web
    restart: always
    entrypoint: bash -c 'echo Serving on http://127.0.0.1:6661 && php -S 0.0.0.0:6661 /app/adminer.php'
    volumes:
      - ./app/database/:/app/
    ports:
      - 6661:6661
    depends_on:
      - db
